In [5]:
#import boto3
import pandas as pd

# Get the service resource.
#dynamodb = boto3.resource('dynamodb')

# Instantiate a table resource object without actually
# creating a DynamoDB table. Note that the attributes of this table
# are lazy-loaded: a request is not made nor are the attribute
# values populated until the attributes
# on the table resource are accessed or its load() method is called.
#table = dynamodb.Table('affidavitdata')

In [17]:

# Read the csv file
df1 = pd.read_csv('../../Data/andhra-pradesh/2009/andhra-pradesh_2009_candidates_MASTER.csv',dtype=str)
df2 = pd.read_csv('../../Data/andhra-pradesh/2014/andhra-pradesh_2014_candidates_MASTER.csv',dtype=str)
df3 = pd.read_csv('../../Data/andhra-pradesh/2019/andhra-pradesh_2019_candidates_MASTER.csv',dtype=str)
df4 = pd.read_csv('../../Data/arunachal-pradesh/2004/arunachal-pradesh_2004_candidates_MASTER.csv',dtype=str)
df5 = pd.read_csv('../../Data/arunachal-pradesh/2009/arunachal-pradesh_2009_candidates_MASTER.csv',dtype=str)
df6 = pd.read_csv('../../Data/arunachal-pradesh/2014/arunachal-pradesh_2014_candidates_MASTER.csv',dtype=str)
df7 = pd.read_csv('../../Data/arunachal-pradesh/2019/arunachal-pradesh_2019_candidates_MASTER.csv',dtype=str)
df8 = pd.read_csv('../../Data/assam/2006/assam_2006_candidates_MASTER.csv',dtype=str)
df9 = pd.read_csv('../../Data/assam/2011/assam_2011_candidates_MASTER.csv',dtype=str)
df10 = pd.read_csv('../../Data/assam/2016/assam_2016_candidates_MASTER.csv',dtype=str)
df11 = pd.read_csv('../../Data/assam/2021/assam_2021_candidates_MASTER.csv',dtype=str)
df12 = pd.read_csv('../../Data/bihar/2005/bihar_2005_candidates_MASTER.csv',dtype=str)
df13 = pd.read_csv('../../Data/bihar/2010/bihar_2010_candidates_MASTER.csv',dtype=str)
df14 = pd.read_csv('../../Data/bihar/2015/bihar_2015_candidates_MASTER.csv',dtype=str)
df15 = pd.read_csv('../../Data/bihar/2020/bihar_2020_candidates_MASTER.csv',dtype=str)
df16 = pd.read_csv('../../Data/chhattisgarh/2008/chhattisgarh_2008_candidates_MASTER.csv',dtype=str)
df17 = pd.read_csv('../../Data/chhattisgarh/2013/chhattisgarh_2013_candidates_MASTER.csv',dtype=str)
df18 = pd.read_csv('../../Data/chhattisgarh/2018/chhattisgarh_2018_candidates_MASTER.csv',dtype=str)
df19 = pd.read_csv('../../Data/delhi/2008/delhi_2008_candidates_MASTER.csv',dtype=str)
df20 = pd.read_csv('../../Data/delhi/2013/delhi_2013_candidates_MASTER.csv',dtype=str)
df21 = pd.read_csv('../../Data/delhi/2015/delhi_2015_candidates_MASTER.csv',dtype=str)
df22 = pd.read_csv('../../Data/delhi/2020/delhi_2020_candidates_MASTER.csv',dtype=str)
df23 = pd.read_csv('../../Data/goa/2007/goa_2007_candidates_MASTER.csv',dtype=str)
df24 = pd.read_csv('../../Data/goa/2012/goa_2012_candidates_MASTER.csv',dtype=str)
df25 = pd.read_csv('../../Data/goa/2017/goa_2017_candidates_MASTER.csv',dtype=str)
df26 = pd.read_csv('../../Data/gujarat/2007/gujarat_2007_candidates_MASTER.csv',dtype=str)
df27 = pd.read_csv('../../Data/gujarat/2012/gujarat_2012_candidates_MASTER.csv',dtype=str)
df28 = pd.read_csv('../../Data/gujarat/2017/gujarat_2017_candidates_MASTER.csv',dtype=str)
df29 = pd.read_csv('../../Data/haryana/2005/haryana_2005_candidates_MASTER.csv',dtype=str)
df30 = pd.read_csv('../../Data/haryana/2009/haryana_2009_candidates_MASTER.csv',dtype=str)
df31 = pd.read_csv('../../Data/haryana/2014/haryana_2014_candidates_MASTER.csv',dtype=str)
df32 = pd.read_csv('../../Data/haryana/2019/haryana_2019_candidates_MASTER.csv',dtype=str)
df33 = pd.read_csv('../../Data/himachal-pradesh/2007/himachal-pradesh_2007_candidates_MASTER.csv',dtype=str)
df34 = pd.read_csv('../../Data/himachal-pradesh/2012/himachal-pradesh_2012_candidates_MASTER.csv',dtype=str)
df35 = pd.read_csv('../../Data/himachal-pradesh/2017/himachal-pradesh_2017_candidates_MASTER.csv',dtype=str)
df36 = pd.read_csv('../../Data/jammu-kashmir/2008/jammu-kashmir_2008_candidates_MASTER.csv',dtype=str)
df37 = pd.read_csv('../../Data/jammu-kashmir/2014/jammu-kashmir_2014_candidates_MASTER.csv',dtype=str)
df38 = pd.read_csv('../../Data/jharkhand/2005/jharkhand_2005_candidates_MASTER.csv',dtype=str)
df39 = pd.read_csv('../../Data/jharkhand/2009/jharkhand_2009_candidates_MASTER.csv',dtype=str)
df40 = pd.read_csv('../../Data/jharkhand/2014/jharkhand_2014_candidates_MASTER.csv',dtype=str)
df41 = pd.read_csv('../../Data/jharkhand/2019/jharkhand_2019_candidates_MASTER.csv',dtype=str)
df42 = pd.read_csv('../../Data/karnataka/2008/karnataka_2008_candidates_MASTER.csv',dtype=str)
df43 = pd.read_csv('../../Data/karnataka/2013/karnataka_2013_candidates_MASTER.csv',dtype=str)
df44 = pd.read_csv('../../Data/karnataka/2018/karnataka_2018_candidates_MASTER.csv',dtype=str)
df45 = pd.read_csv('../../Data/kerala/2006/kerala_2006_candidates_MASTER.csv',dtype=str)
df46 = pd.read_csv('../../Data/kerala/2011/kerala_2011_candidates_MASTER.csv',dtype=str)
df47 = pd.read_csv('../../Data/kerala/2016/kerala_2016_candidates_MASTER.csv',dtype=str)
df48 = pd.read_csv('../../Data/kerala/2021/kerala_2021_candidates_MASTER.csv',dtype=str)
df49 = pd.read_csv('../../Data/lok-sabha/2004/lok-sabha_2004_candidates_MASTER.csv',dtype=str)
df50 = pd.read_csv('../../Data/lok-sabha/2009/lok-sabha_2009_candidates_MASTER.csv',dtype=str)
df51 = pd.read_csv('../../Data/lok-sabha/2014/lok-sabha_2014_candidates_MASTER.csv',dtype=str)
df52 = pd.read_csv('../../Data/lok-sabha/2019/lok-sabha_2019_candidates_MASTER.csv',dtype=str)
df53 = pd.read_csv('../../Data/madhya-pradesh/2008/madhya-pradesh_2008_candidates_MASTER.csv',dtype=str)
df54 = pd.read_csv('../../Data/madhya-pradesh/2013/madhya-pradesh_2013_candidates_MASTER.csv',dtype=str)
df55 = pd.read_csv('../../Data/madhya-pradesh/2018/madhya-pradesh_2018_candidates_MASTER.csv',dtype=str)
df56 = pd.read_csv('../../Data/maharashtra/2004/maharashtra_2004_candidates_MASTER.csv',dtype=str)
df57 = pd.read_csv('../../Data/maharashtra/2009/maharashtra_2009_candidates_MASTER.csv',dtype=str)
df58 = pd.read_csv('../../Data/maharashtra/2014/maharashtra_2014_candidates_MASTER.csv',dtype=str)
df59 = pd.read_csv('../../Data/maharashtra/2019/maharashtra_2019_candidates_MASTER.csv',dtype=str)
df60 = pd.read_csv('../../Data/manipur/2007/manipur_2007_candidates_MASTER.csv',dtype=str)
df61 = pd.read_csv('../../Data/manipur/2012/manipur_2012_candidates_MASTER.csv',dtype=str)
df62 = pd.read_csv('../../Data/manipur/2017/manipur_2017_candidates_MASTER.csv',dtype=str)
df63 = pd.read_csv('../../Data/meghalaya/2008/meghalaya_2008_candidates_MASTER.csv',dtype=str)
df64 = pd.read_csv('../../Data/meghalaya/2013/meghalaya_2013_candidates_MASTER.csv',dtype=str)
df65 = pd.read_csv('../../Data/meghalaya/2018/meghalaya_2018_candidates_MASTER.csv',dtype=str)
df66 = pd.read_csv('../../Data/mizoram/2008/mizoram_2008_candidates_MASTER.csv',dtype=str)
df67 = pd.read_csv('../../Data/mizoram/2013/mizoram_2013_candidates_MASTER.csv',dtype=str)
df68 = pd.read_csv('../../Data/mizoram/2018/mizoram_2018_candidates_MASTER.csv',dtype=str)
df69 = pd.read_csv('../../Data/nagaland/2008/nagaland_2008_candidates_MASTER.csv',dtype=str)
df70 = pd.read_csv('../../Data/nagaland/2013/nagaland_2013_candidates_MASTER.csv',dtype=str)
df71 = pd.read_csv('../../Data/nagaland/2018/nagaland_2018_candidates_MASTER.csv',dtype=str)
df72 = pd.read_csv('../../Data/odisha/2004/odisha_2004_candidates_MASTER.csv',dtype=str)
df73 = pd.read_csv('../../Data/odisha/2009/odisha_2009_candidates_MASTER.csv',dtype=str)
df74 = pd.read_csv('../../Data/odisha/2014/odisha_2014_candidates_MASTER.csv',dtype=str)
df75 = pd.read_csv('../../Data/odisha/2019/odisha_2019_candidates_MASTER.csv',dtype=str)
df76 = pd.read_csv('../../Data/puducherry/2006/puducherry_2006_candidates_MASTER.csv',dtype=str)
df77 = pd.read_csv('../../Data/puducherry/2011/puducherry_2011_candidates_MASTER.csv',dtype=str)
df78 = pd.read_csv('../../Data/puducherry/2016/puducherry_2016_candidates_MASTER.csv',dtype=str)
df79 = pd.read_csv('../../Data/puducherry/2021/puducherry_2021_candidates_MASTER.csv',dtype=str)
df80 = pd.read_csv('../../Data/punjab/2007/punjab_2007_candidates_MASTER.csv',dtype=str)
df81 = pd.read_csv('../../Data/punjab/2012/punjab_2012_candidates_MASTER.csv',dtype=str)
df82 = pd.read_csv('../../Data/punjab/2017/punjab_2017_candidates_MASTER.csv',dtype=str)
df83 = pd.read_csv('../../Data/punjab/2022/punjab_2022_candidates_MASTER.csv',dtype=str)
df84 = pd.read_csv('../../Data/rajasthan/2008/rajasthan_2008_candidates_MASTER.csv',dtype=str)
df85 = pd.read_csv('../../Data/rajasthan/2013/rajasthan_2013_candidates_MASTER.csv',dtype=str)
df86 = pd.read_csv('../../Data/rajasthan/2018/rajasthan_2018_candidates_MASTER.csv',dtype=str)
df87 = pd.read_csv('../../Data/sikkim/2004/sikkim_2004_candidates_MASTER.csv',dtype=str)
df88 = pd.read_csv('../../Data/sikkim/2009/sikkim_2009_candidates_MASTER.csv',dtype=str)
df89 = pd.read_csv('../../Data/sikkim/2014/sikkim_2014_candidates_MASTER.csv',dtype=str)
df90 = pd.read_csv('../../Data/sikkim/2019/sikkim_2019_candidates_MASTER.csv',dtype=str)
df91 = pd.read_csv('../../Data/tamil-nadu/2006/tamil-nadu_2006_candidates_MASTER.csv',dtype=str)
df92 = pd.read_csv('../../Data/tamil-nadu/2011/tamil-nadu_2011_candidates_MASTER.csv',dtype=str)
df93 = pd.read_csv('../../Data/tamil-nadu/2016/tamil-nadu_2016_candidates_MASTER.csv',dtype=str)
df94 = pd.read_csv('../../Data/tamil-nadu/2021/tamil-nadu_2021_candidates_MASTER.csv',dtype=str)
df95 = pd.read_csv('../../Data/telangana/2014/telangana_2014_candidates_MASTER.csv',dtype=str)
df96 = pd.read_csv('../../Data/telangana/2018/telangana_2018_candidates_MASTER.csv',dtype=str)
df97 = pd.read_csv('../../Data/tripura/2008/tripura_2008_candidates_MASTER.csv',dtype=str)
df98 = pd.read_csv('../../Data/tripura/2013/tripura_2013_candidates_MASTER.csv',dtype=str)
df99 = pd.read_csv('../../Data/tripura/2018/tripura_2018_candidates_MASTER.csv',dtype=str)
df100 = pd.read_csv('../../Data/up/2007/uttar-pradesh_2007_candidates_MASTER.csv',dtype=str)
df101 = pd.read_csv('../../Data/up/2012/uttar-pradesh_2012_candidates_MASTER.csv',dtype=str)
df102 = pd.read_csv('../../Data/up/2017/uttar-pradesh_2017_candidates_MASTER.csv',dtype=str)
df103 = pd.read_csv('../../Data/up/2022/uttar-pradesh_2022_candidates_MASTER.csv',dtype=str)
df104 = pd.read_csv('../../Data/uttar-pradesh/2007/uttar-pradesh_2007_candidates_MASTER.csv',dtype=str)
df105 = pd.read_csv('../../Data/uttar-pradesh/2012/uttar-pradesh_2012_candidates_MASTER.csv',dtype=str)
df106 = pd.read_csv('../../Data/uttar-pradesh/2017/uttar-pradesh_2017_candidates_MASTER.csv',dtype=str)
df107 = pd.read_csv('../../Data/uttar-pradesh/2022/uttar-pradesh_2022_candidates_MASTER.csv',dtype=str)
df108 = pd.read_csv('../../Data/uttarakhand/2007/uttarakhand_2007_candidates_MASTER.csv',dtype=str)
df109 = pd.read_csv('../../Data/uttarakhand/2012/uttarakhand_2012_candidates_MASTER.csv',dtype=str)
df110 = pd.read_csv('../../Data/uttarakhand/2017/uttarakhand_2017_candidates_MASTER.csv',dtype=str)
df111 = pd.read_csv('../../Data/west-bengal/2006/west-bengal_2006_candidates_MASTER.csv',dtype=str)
df112 = pd.read_csv('../../Data/west-bengal/2011/west-bengal_2011_candidates_MASTER.csv',dtype=str)
df113 = pd.read_csv('../../Data/west-bengal/2016/west-bengal_2016_candidates_MASTER.csv',dtype=str)
df114 = pd.read_csv('../../Data/west-bengal/2021/west-bengal_2021_candidates_MASTER.csv',dtype=str)

#Data\up\2017\uttar-pradesh_2017_candidates_MASTER.csv
#Data\up\2012\uttar-pradesh_2012_candidates_MASTER.csv
#Data\up\2007\uttar-pradesh_2007_candidates_MASTER.csv
# First 5 row()s
df = pd.concat([df1
 ,df2
 ,df3
 ,df4
 ,df5
 ,df6
 ,df7
 ,df8
 ,df9
 ,df10
 ,df11
 ,df12
 ,df13
 ,df14
 ,df15
 ,df16
 ,df17
 ,df18
 ,df19
 ,df20
 ,df21
 ,df22
 ,df23
 ,df24
 ,df25
 ,df26
 ,df27
 ,df28
 ,df29
 ,df30
 ,df31
 ,df32
 ,df33
 ,df34
 ,df35
 ,df36
 ,df37
 ,df38
 ,df39
 ,df40
 ,df41
 ,df42
 ,df43
 ,df44
 ,df45
 ,df46
 ,df47
 ,df48
 ,df49
 ,df50
 ,df51
 ,df52
 ,df53
 ,df54
 ,df55
 ,df56
 ,df57
 ,df58
 ,df59
 ,df60
 ,df61
 ,df62
 ,df63
 ,df64
 ,df65
 ,df66
 ,df67
 ,df68
 ,df69
 ,df70
 ,df71
 ,df72
 ,df73
 ,df74
 ,df75
 ,df76
 ,df77
 ,df78
 ,df79
 ,df80
 ,df81
 ,df82
 ,df83
 ,df84
 ,df85
 ,df86
 ,df87
 ,df88
 ,df89
 ,df90
 ,df91
 ,df92
 ,df93
 ,df94
 ,df95
 ,df96
 ,df97
 ,df98
 ,df99
 ,df100
 ,df101
 ,df102
 ,df103
 ,df104
 ,df105
 ,df106
 ,df107
 ,df108
 ,df109
 ,df110
 ,df111
 ,df112
 ,df113
 ,df114

])

print('::::::::::Count Stats::::::::::::::::::::')


print(df.shape)
print('::::::::::::::combined::::::::::::::::')
df.info()

::::::::::Count Stats::::::::::::::::::::
(174186, 34)
::::::::::::::combined::::::::::::::::
<class 'pandas.core.frame.DataFrame'>
Int64Index: 174186 entries, 0 to 2129
Data columns (total 34 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   state                        174154 non-null  object
 1   year                         174154 non-null  object
 2   constituency                 174186 non-null  object
 3   ac_no                        155194 non-null  object
 4   district                     170544 non-null  object
 5   sub_region                   104659 non-null  object
 6   reservations                 155194 non-null  object
 7   candidate_name               174186 non-null  object
 8   party                        174185 non-null  object
 9   party_eci                    166869 non-null  object
 10  url                          174186 non-null  object
 11  winner                       174154 non-null  object
 12  gender                       174173 non-null  object
 13  age                          172927 non-null  object
 14  so_do                        173559 non-null  object
 15  address                      166347 non-null  object
 16  profession                   120853 non-null  object
 17  spouse_profession            103054 non-null  object
 18  criminal_cases               174186 non-null  object
 19  serious_criminal_cases       173877 non-null  object
 20  education                    174186 non-null  object
 21  assets                       174186 non-null  object
 22  liabilities                  174186 non-null  object
 23  net_assets                   174186 non-null  object
 24  filed_itr                    125005 non-null  object
 25  declared_pan                 174186 non-null  object
 26  recontest_url                8809 non-null    object
 27  recontest_assets_this        8809 non-null    object
 28  recontest_assets_last        8806 non-null    object
 29  recontest_assets_change      8658 non-null    object
 30  recontest_remarks            4458 non-null    object
 31  email                        398 non-null     object
 32  phone                        852 non-null     object
 33  recontest_assets_change_pct  164 non-null     object
dtypes: object(34)
memory usage: 46.5+ MB

In [18]:
df.head()

,state,year,constituency,ac_no,district,sub_region,reservations,candidate_name,party,party_eci,...,filed_itr,declared_pan,recontest_url,recontest_assets_this,recontest_assets_last,recontest_assets_change,recontest_remarks,email,phone,recontest_assets_change_pct
0,Andhra Pradesh,2009,GHANPUR (STATION) (SC),99,WARANGAL,TELANGANA,SC,Daida. Christoper,Ajeya Bharat Party,Ajeya Bharat Party,...,NaN,FALSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Andhra Pradesh,2009,NARASARAOPET,216,GUNTUR,COASTAL ANDHRA,GEN,Eswaraiah Pakala,Ajeya Bharat Party,Ajeya Bharat Party,...,NaN,FALSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Andhra Pradesh,2009,PEDAKURAPADU,204,GUNTUR,COASTAL ANDHRA,GEN,Kannedari Seshagiri Rao,Ajeya Bharat Party,Ajeya Bharat Party,...,NaN,FALSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Andhra Pradesh,2009,CHOPPADANDI (SC),27,KARIMANAGAR,TELANGANA,SC,LANKA ANJAIAH,Ajeya Bharat Party,Ajeya Bharat Party,...,NaN,FALSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Andhra Pradesh,2009,NAMPALLI,63,HYDERABAD,TELANGANA,GEN,Syed Siddique Akbar Ali,Ajeya Bharat Party,Ajeya Bharat Party,...,NaN,FALSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
df.columns

Index(['state', 'year', 'constituency', 'ac_no', 'district', 'sub_region',
       'reservations', 'candidate_name', 'party', 'party_eci', 'url', 'winner',
       'gender', 'age', 'so_do', 'address', 'profession', 'spouse_profession',
       'criminal_cases', 'serious_criminal_cases', 'education', 'assets',
       'liabilities', 'net_assets', 'filed_itr', 'declared_pan',
       'recontest_url', 'recontest_assets_this', 'recontest_assets_last',
       'recontest_assets_change', 'recontest_remarks'],
      dtype='object')

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 174186 entries, 0 to 2129
Data columns (total 34 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   state                        174154 non-null  object
 1   year                         174154 non-null  object
 2   constituency                 174186 non-null  object
 3   ac_no                        155194 non-null  object
 4   district                     170544 non-null  object
 5   sub_region                   104659 non-null  object
 6   reservations                 155194 non-null  object
 7   candidate_name               174186 non-null  object
 8   party                        174185 non-null  object
 9   party_eci                    166869 non-null  object
 10  url                          174186 non-null  object
 11  winner                       174154 non-null  object
 12  gender                       174173 non-null  object
 13  age                          172927 non-null  object
 14  so_do                        173559 non-null  object
 15  address                      166347 non-null  object
 16  profession                   120853 non-null  object
 17  spouse_profession            103054 non-null  object
 18  criminal_cases               174186 non-null  object
 19  serious_criminal_cases       173877 non-null  object
 20  education                    174186 non-null  object
 21  assets                       174186 non-null  object
 22  liabilities                  174186 non-null  object
 23  net_assets                   174186 non-null  object
 24  filed_itr                    125005 non-null  object
 25  declared_pan                 174186 non-null  object
 26  recontest_url                8809 non-null    object
 27  recontest_assets_this        8809 non-null    object
 28  recontest_assets_last        8806 non-null    object
 29  recontest_assets_change      8658 non-null    object
 30  recontest_remarks            4458 non-null    object
 31  email                        398 non-null     object
 32  phone                        852 non-null     object
 33  recontest_assets_change_pct  164 non-null     object
dtypes: object(34)
memory usage: 46.5+ MB

In [21]:
df=df.dropna(axis=1,how='all')


df['age']= df['age'].fillna('NOT_AVAILABLE')
df['so_do']= df['so_do'].fillna('NOT_AVAILABLE')
df['address']= df['address'].fillna('NOT_AVAILABLE')
df['ac_no']= df['ac_no'].fillna('NOT_AVAILABLE')
df['sub_region']= df['sub_region'].fillna('NOT_AVAILABLE')
df['reservations']= df['reservations'].fillna('NOT_AVAILABLE')
df['party_eci']= df['party_eci'].fillna('NOT_AVAILABLE')
df['profession']= df['profession'].fillna('NOT_AVAILABLE')
df['spouse_profession']= df['spouse_profession'].fillna('NOT_AVAILABLE')
df['recontest_url']= df['recontest_url'].fillna('NOT_AVAILABLE')
df['filed_itr']= df['filed_itr'].fillna('NOT_AVAILABLE')
df['recontest_assets_this']= df['recontest_assets_this'].fillna('NOT_AVAILABLE')

df['recontest_assets_last']= df['recontest_assets_last'].fillna('NOT_AVAILABLE')

df['recontest_assets_change']= df['recontest_assets_change'].fillna('NOT_AVAILABLE')

df['recontest_remarks']= df['recontest_remarks'].fillna('NOT_AVAILABLE')

df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 174186 entries, 0 to 2129
Data columns (total 34 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   state                        174154 non-null  object
 1   year                         174154 non-null  object
 2   constituency                 174186 non-null  object
 3   ac_no                        174186 non-null  object
 4   district                     170544 non-null  object
 5   sub_region                   174186 non-null  object
 6   reservations                 174186 non-null  object
 7   candidate_name               174186 non-null  object
 8   party                        174185 non-null  object
 9   party_eci                    174186 non-null  object
 10  url                          174186 non-null  object
 11  winner                       174154 non-null  object
 12  gender                       174173 non-null  object
 13  age                          174186 non-null  object
 14  so_do                        174186 non-null  object
 15  address                      174186 non-null  object
 16  profession                   174186 non-null  object
 17  spouse_profession            174186 non-null  object
 18  criminal_cases               174186 non-null  object
 19  serious_criminal_cases       173877 non-null  object
 20  education                    174186 non-null  object
 21  assets                       174186 non-null  object
 22  liabilities                  174186 non-null  object
 23  net_assets                   174186 non-null  object
 24  filed_itr                    174186 non-null  object
 25  declared_pan                 174186 non-null  object
 26  recontest_url                174186 non-null  object
 27  recontest_assets_this        174186 non-null  object
 28  recontest_assets_last        174186 non-null  object
 29  recontest_assets_change      174186 non-null  object
 30  recontest_remarks            174186 non-null  object
 31  email                        398 non-null     object
 32  phone                        852 non-null     object
 33  recontest_assets_change_pct  164 non-null     object
dtypes: object(34)
memory usage: 46.5+ MB

In [13]:
df.head()

,state,year,constituency,ac_no,district,sub_region,reservations,candidate_name,party,party_eci,...,net_assets,filed_itr,declared_pan,recontest_url,recontest_assets_this,recontest_assets_last,recontest_assets_change,recontest_remarks,CandidateID,id_year
0,Uttar Pradesh,2022,LUCKNOW EAST,NOT_AVAILABLE,LUCKNOW,NOT_AVAILABLE,NOT_AVAILABLE,Aashish Kumar Sinha,BSP,NOT_AVAILABLE,...,64776317,true,true,NOT_AVAILABLE,NOT_AVAILABLE,NOT_AVAILABLE,NOT_AVAILABLE,NOT_AVAILABLE,2667,2022_UP_2667
1,Uttar Pradesh,2022,HASANPUR,NOT_AVAILABLE,AMROHA,NOT_AVAILABLE,NOT_AVAILABLE,Aasim Sabri,INC,NOT_AVAILABLE,...,45761798,true,true,NOT_AVAILABLE,NOT_AVAILABLE,NOT_AVAILABLE,NOT_AVAILABLE,NOT_AVAILABLE,1583,2022_UP_1583
2,Uttar Pradesh,2022,BITHARI CHAINPUR,NOT_AVAILABLE,BAREILLY,NOT_AVAILABLE,NOT_AVAILABLE,Abdul Fahim,IND,NOT_AVAILABLE,...,3028026,true,true,NOT_AVAILABLE,NOT_AVAILABLE,NOT_AVAILABLE,NOT_AVAILABLE,NOT_AVAILABLE,1073,2022_UP_1073
3,Uttar Pradesh,2022,HASANPUR,NOT_AVAILABLE,AMROHA,NOT_AVAILABLE,NOT_AVAILABLE,Abdul Khaliq,Naki Bharatiya Ekta Party,NOT_AVAILABLE,...,1753000,true,true,NOT_AVAILABLE,NOT_AVAILABLE,NOT_AVAILABLE,NOT_AVAILABLE,NOT_AVAILABLE,1579,2022_UP_1579
4,Uttar Pradesh,2022,SANDILA,NOT_AVAILABLE,HARDOI,NOT_AVAILABLE,NOT_AVAILABLE,Abdul Mannan,BSP,NOT_AVAILABLE,...,48647299,true,true,NOT_AVAILABLE,NOT_AVAILABLE,NOT_AVAILABLE,NOT_AVAILABLE,NOT_AVAILABLE,2612,2022_UP_2612

In [26]:
df['educationNum'] = df['education'].replace(['Graduate Professional', 'Not Given', '10th Pass', '8th Pass',
       'Graduate', '12th Pass', 'Literate', 'Post Graduate', 'Illiterate',
       '5th Pass', 'Doctorate', 'Others'], [22,0,15,8,21,17,15,25,0,5,30,15])

In [28]:
df = df[['state','year','constituency','district','educationNum','winner','gender','criminal_cases','serious_criminal_cases','assets','liabilities','net_assets']]

In [29]:
df.to_csv('all-need.csv')

In [49]:
sd2 = df['state']+"-"+df['district']
#sd2 = sd2.unique()
sd2.to_csv('all-sd.csv')

In [47]:
df['state'] = df['state'].replace(['Arunachal Pradesh','Delhi'],['Arunanchal Pradesh','NCT of Delhi'])